origin: main.c species.c ivector.c specieslist.c utils.c graph.c
	gcc -O3 -DHAVE_INLINE -DNDEBUG -DOINLINING -std=c99 main.c species.c ivector.c specieslist.c utils.c graph.c -o origin -lgsl -lgslcblas -lpthread -lm
